<div id="menu-bar" class="navbar">
<div class="navbar-inner">
<ul id="main-menu" class="nav">
    <?php foreach($this->container as $page)
    {
        $url = array();
        if ( isset($page->url) && $page->url != "" )
        {
            $url = $page->url;
            if ( isset($url['activity']) && $url['activity'] != "" )
                $url['activity'] = urlencode($url['activity']);
        }
        $page->url = $this->url($url, null, true);
        echo '<li><a href="' . $page->url . '">' . $page->label . '</li></a>';
    }
    ?>
</ul>
<p class="pull-right navbar-text"><?php echo $this->loggedInUser(); ?></p></div></div>
