<?php
/* This helper script expects an array of button labels.
*/

// Technique for turning button labels into valid name identifiers taken
// from Zend_Form_Element.
$charset = '^a-zA-Z0-9_\x7f-\xff';
?>
<div class='span3 pull-right'>
<div id="title-sidebar" class='sidebar-nav'>
<fieldset id="button-list" class="sidebar">
<ul class='nav nav-tabs nav-stacked'>

<?php
foreach ( $this->buttonList as $buttonLabel ) :
    $buttonType = ( $buttonLabel == TableController::RESET_BUTTON ) ?
                        "reset" : "submit";
    $buttonLabel = $this->escape($buttonLabel);
    $buttonId = $this->escape(preg_replace('/[' . $charset . ']/', '', 
                                    (string) $buttonLabel));
    echo "<li><a class='btn btn-link'><input type='$buttonType' name='submit' id='$buttonId'
            value='$buttonLabel' class='btn btn-link' /></a></li>\n";
endforeach;
?>

</ul>
</fieldset>
</div>
</div>
